### ISSUE TITLE
Provide ready to use URL 

### ISSUE THREAD

**Issue by tyohan** [inlivedev/inlive-js-sdk#28]
It will be great to provide ready to use URL that we can use to copy and paste into the script URL. So on HTML page, we can just include it like this:
```
<script src="https://inlive-sdk-url"></script>
```

The script should be bundled and minified.

**Comment by faiq-naufal** [comment]
Mas @tyohan, when we publish the SDK to the NPM, some free CDN services provide the access to the SDK directly through URL automatically. From version `0.3.0` our SDK was already bundled into a single file called `inlive-js-sdk.js`. When we access the SDK through the URL, we need to access that bundle file.

These are the ways we can access our SDK through some free CDN services.

**unpkg**

```bash
# Access the latest version
https://unpkg.com/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js

# Access the specific 0.3.0 version
https://unpkg.com/@inlivedev/inlive-js-sdk@0.3.0/dist/inlive-js-sdk.js
```

**jsdelivr**

```bash
# Access the latest version
https://cdn.jsdelivr.net/npm/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js

# Access the specific 0.3.0 version
https://cdn.jsdelivr.net/npm/@inlivedev/inlive-js-sdk@0.3.0/dist/inlive-js-sdk.js
```

**skypack**

```bash
# Access the latest version
https://cdn.skypack.dev/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js

# Access the specific 0.3.0 version
https://cdn.skypack.dev/@inlivedev/inlive-js-sdk@0.3.0/dist/inlive-js-sdk.js
```

Using those URL, we can just import the module we want to use. For example:

```js
import { InliveStream } from 'https://unpkg.com/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js'

import { InliveStream } from 'https://cdn.jsdelivr.net/npm/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js'

import { InliveStream } from 'https://cdn.skypack.dev/@inlivedev/inlive-js-sdk/dist/inlive-js-sdk.js'
```
