### ISSUE TITLE
Automatically fallback to simulcast h264 if VP9 is not available

### ISSUE THREAD

**Issue by tyohan** [inlivedev/inlive-js-sdk#77]
The room package currently use VP9 as default codec and enable SVC when publishing a video track. There is a possibility that user does not have a latest OS of iOS or MacOS, and their Safari browser doesn't support VP9 for WebRTC. In this case, the SDK should fallback to H264 and allow them to publish the video track using simulcast.

**Comment by faiq-naufal** [comment]
After this PR #96 merged, this issue has been resolved. By default when video/VP9 codec is not supported, sdk will fallback to video/H264.
